name: Lux CLI CI

on:
  push:
    branches: [main]
    paths:
      - 'lux_cli/**'
  pull_request:
    branches: [main]
    paths:
      - 'lux_cli/**'

jobs:
  test:
    name: Build and Test Lux CLI
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: lux_cli
    steps:
      - uses: actions/checkout@v4

      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          otp-version: 'OTP-27.2'
          elixir-version: 'v1.18.1-otp-27'

      - name: Cache Mix deps
        uses: actions/cache@v3
        with:
          path: |
            lux_cli/deps
            lux_cli/_build
          key: ${{ runner.os }}-mix-lux-cli-${{ hashFiles('lux_cli/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-mix-lux-cli-

      - name: Cache Dialyzer PLTs
        uses: actions/cache@v3
        with:
          path: lux_cli/priv/plts
          key: ${{ runner.os }}-dialyzer-lux-cli-${{ hashFiles('lux_cli/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-dialyzer-lux-cli-

      - name: Install Mix Dependencies
        run: mix deps.get

      - name: Create PLT directory
        run: mkdir -p priv/plts

      - name: Check Formatting
        run: mix format --check-formatted

      - name: Run Credo
        run: mix credo

      - name: Run Dialyzer
        run: mix dialyzer

      - name: Run Tests
        run: mix test

      - name: Build Escript
        run: mix escript.build 